version: '3.3'
services:
  mysql:
    image: mysql:8.0.27
    platform: linux/amd64
    command: "mysqld --character-set-server=utf8"
    environment:
      MYSQL_ROOT_PASSWORD: local
      MYSQL_DATABASE: small-clawed-otter
      MYSQL_USER: local
      MYSQL_PASSWORD: local
    ports:
      - "3318:3306"